spring.application.name=springjwt
logging.level.root=ERROR
logging.level.org.springframework.boot.tomcat=INFO
logging.level.org.springframework.boot.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.secret=0e2574f781cdb35762398b4e2291aa072bd8d80ad6880d07f72da350c9b09ef0